version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: mi-redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  postgres:
    image: postgres:15-alpine
    container_name: my-postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: john.angel
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  localstack:
    image: localstack/localstack:3.0
    container_name: mi-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs, dynamodb
      - DEFAULT_REGION=us-east-1
    volumes:
      - localstack_data:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  redis_data:
  postgres_data:
  localstack_data: