server:
  port: 8080
spring:
  application:
    name: "users"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
    active: local
  redis:
    host: "localhost"
    port: 6379
  sql:
    init:
      mode: "always"
      platform: "postgresql"
  cloud:
    aws:
      region:
        static: "us-east-1"
        auto: false
      endpoint: "http://localhost:4566"
      credentials:
        access-key: "test"
        secret-key: "test"
      sqs:
        queue-name: "user_created_queue"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "usersdb"
    schema: "public"
    username: "john.angel"
    password: "postgres"
adapter:
  restconsumer:
    timeout: 5000
    url: "https://reqres.in/api"
    apikey: "reqres-free-v1"
  redis:
    ttl: 3600000
  sqs:
    region: "us-east-1"
    queueUrl: "http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/user_created_queue"
    endpoint: "http://localhost:4566"
resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
entrypoint:
  sqs:
    region: "us-east-1"
    endpoint: "http://localhost:4566"
    queueUrl: "http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/user_created_queue"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
aws:
  region: "us-east-1"
  dynamodb:
    endpoint: "http://localhost:4566"
